import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import Navbar from "@/components/navigation/navbar"
import { ThemeProvider } from "next-themes"

const raleway = localFont({
  src: "./fonts/RalewayVF.ttf",
  weight: "100 200 300 400 500 600 700 800 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <body className={`${raleway.className} antialiased`}>
          <ThemeProvider defaultTheme="system">
            <Navbar />
            {children}
          </ThemeProvider>
        </body>
      </head>
    </html>
  )
}
